repos:
  - repo: https://github.com/psf/black
    rev: 23.1a1
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        additional_dependencies: ["prettier@3.1.0"]
        files: "\\.(js|jsx|ts|tsx|css|scss|less|json|yaml|yml|md)$"

  - repo: https://github.com/djlint/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django
