# Uses Compose Specification (https://github.com/compose-spec/compose-spec/blob/master/spec.md)
services:
  app:
    build:
      context: .
      dockerfile: ./web-app/Dockerfile
      args:
        - DEVELOPMENT=$DEVELOPMENT
    container_name: vim-app
    volumes:
      - ./web-app/django:/virtual-instrument-museum/vim-app
      - vim-static:/virtual-instrument-museum/static
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - HOST_NAME=${HOST_NAME}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    command: /virtual-instrument-museum/django-startup.sh

  postgres:
    image: postgres:15.4
    container_name: vim-db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  nginx:
    build: ./nginx
    container_name: vim-nginx
    restart: unless-stopped
    environment:
      - HOST_NAME=${HOST_NAME}
    ports:
      - "${PORT}:80"
    volumes:
      - vim-static:/virtual-instrument-museum/static
    depends_on:
      - app

  solr:
    build: ./solr
    container_name: vim-solr
    restart: unless-stopped
    ports:
      - "8983:8983"

networks:
  vim-net:


volumes:
  vim-static:
