# Generated by Django 4.2.5 on 2023-09-27 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AVResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('image', 'Image')], help_text='What type of audiovisual resource is this?', max_length=5)),
                ('format', models.CharField()),
                ('url', models.URLField(max_length=1000)),
                ('instrument_date', models.DateField(blank=True, help_text='When was this instrument made?', null=True)),
                ('instrument_maker', models.CharField(blank=True, help_text='Who made this instrument?')),
                ('instrument_description', models.TextField(blank=True, help_text='Additional information about the instrument.')),
                ('source_name', models.CharField(help_text='What is the name of the source of this AVResource?')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wikidata_id', models.CharField(max_length=20, unique=True)),
                ('hornbostel_sachs_class', models.CharField(blank=True, help_text='Hornbostel-Sachs classification', max_length=50)),
                ('mimo_class', models.CharField(blank=True, help_text='Musical Instrument Museums Online classification', max_length=50)),
                ('default_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_image_of', to='instruments.avresource')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wikidata_code', models.CharField(help_text='Language code in Wikidata', unique=True)),
                ('wikidata_id', models.CharField(help_text='Language ID (Q number) in Wikidata', unique=True)),
                ('en_label', models.CharField(help_text='Language label in English')),
                ('autonym', models.CharField(help_text='Language label in the language itself')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('source_name', models.CharField(help_text='Who or what called the instrument this?', max_length=50)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.instrument')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.language')),
            ],
        ),
        migrations.AddField(
            model_name='avresource',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.instrument'),
        ),
        migrations.AddField(
            model_name='avresource',
            name='instrument_description_language',
            field=models.ForeignKey(blank=True, help_text='What language is Instrument Description written in?', null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.language'),
        ),
    ]
