# Generated by Django 4.2.5 on 2024-08-13 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrument",
            name="thumbnail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="thumbnail_of",
                to="instruments.avresource",
            ),
        ),
    ]
