# Generated by Django 4.2.5 on 2024-08-16 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0003_alter_avresource_instrument_and_more"),
        ("instruments", "0003_alter_instrumentname_name"),
    ]

    operations = []
