# Generated by Django 4.2.5 on 2024-09-23 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0004_merge_20240816_2008"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="language",
            name="wikidata_id",
        ),
    ]
